example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist, show_wishlist_xml, show_wishlist_json, get_one_json, get_one_xml, register, login_user, logout_user , show_wishlist_ajax, add_wishlist_ajax

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_wishlist_xml, name='show_wishlist_xml'), 
    path('xml/<int:id>', get_one_xml, name='get_one_xml'), 
    path('json/', show_wishlist_json, name='show_wishlist_json'), 
    path('json/<int:id>', get_one_json, name='get_one_json'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit/', add_wishlist_ajax, name='add_wishlist_ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

wishlist/forms.py
from django import forms
from wishlist.models import BarangWishlist

class CreateWishlistForm(forms.ModelForm):

    class Meta:
        model = BarangWishlist
        fields = ('nama_barang', 'harga_barang', 'deskripsi')

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.core import serializers
from django.shortcuts import render, redirect
from wishlist.forms import CreateWishlistForm
from wishlist.models import BarangWishlist
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': request.user.username,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

def show_wishlist_xml(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data_barang_wishlist), content_type="application/xml")

def show_wishlist_json(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data_barang_wishlist), content_type="application/json")

def get_one_xml(request, id):
    data_satu_barang = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data_satu_barang), content_type="application/xml")

def get_one_json(request, id):
    data_satu_barang = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data_satu_barang), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': request.user.username,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html",context)

@login_required(login_url='/wishlist/login/')
def add_wishlist_ajax(request):
    form = CreateWishlistForm()

    if request.method == "POST":
        form = CreateWishlistForm(request.POST)
        if form.is_valid():
            form.save() 
            messages.success(request, 'Wishlist telah berhasil dibuat!')
            return redirect('wishlist:show_wishlist_ajax')
    
    context = {'form':form,     
        'nama': request.user.username,}
    return render(request, 'wishlist_ajax_submit.html', context)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
  <h4>Apps list</>
  <li>
    <a class="btn btn-outline-dark" href="/wishlist/">Wishlist</a>
  </li>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block meta %}
    {% endblock meta %}
  </head>
  
  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <div class="container-fluid">
    <h1>Login</h1>
    <form method="POST" action="">
        {% csrf_token %}
        <table class="space-x-5">
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

        </table>


            <button class="btn btn-dark" value="login" type="submit">Login</button>
        </tr>
    </form>


    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a class="btn btn-link" href="{% url 'wishlist:register' %}">Buat Akun</a>
</div>
</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
            </table>  
            <button class="btn btn-dark" type="submit">Daftar</button>
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-light ">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Hi, {{nama}}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'example_app:index' %}">Home</a>
            </li>
        </ul>
        <span class="navbar-text">
            <button class="btn btn-dark" onclick="location.href=`{% url 'wishlist:logout' %}`">Logout</button>
        </span>
        </div>
    </div>
</nav>

<div class="container ">

    <table class="table table-striped table-bordered my-5">
        <thead >
            <tr>
                <th scope="col">Nama Barang</th>
                <th scope="col">Harga Barang</th>
                <th scope="col">Deskripsi</th>
            </tr>
        </thead>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        {% for barang in list_barang %}
        <tr scope="row">
            <td>{{barang.nama_barang}}</td>
            <td>{{barang.harga_barang}}</td>
            <td>{{barang.deskripsi}}</td>
        </tr>
        {% endfor %}
    </table>
    
    <p>Sesi terakhir login: {{ last_login }}</p>
</div>
    
    
{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}
{% block content %}
<!-- buat get sm post -->
{% block meta %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!-- contoh  -->
<script>
    $(document).ready(function(){
        $.getJSON("{% url 'wishlist:show_wishlist_json' %}", function(data) { //ambil dari wishlist
            $.each(data, function(key){
                $("#wishlist-ajax").append("<tr>\
										<td>"+data[key].fields.nama_barang+"</td>\
										<td>"+data[key].fields.harga_barang+"</td>\
										<td>"+data[key].fields.deskripsi+"</td>\
										</tr>");
                                    });
            })
        });

    </script>
{% endblock meta %}
<nav class="navbar navbar-expand-lg bg-light ">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Hi, {{nama}}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'example_app:index' %}">Home</a>
            </li>
        </ul>
        <span class="navbar-text">
            <button class="btn btn-dark" onclick="location.href=`{% url 'wishlist:logout' %}`">Logout</button>
        </span>
        </div>
    </div>
</nav>


<div class="container ">

    <table class="table table-striped table-bordered my-5" id="wishlist-ajax">
    </table>

    <p>Sesi terakhir login: {{ last_login }}</p>
    <form method="POST" >
        {% csrf_token %} 
        {{ form.as_table }}
    </form>
    <button  class="btn btn-secondary" onclick="location.href=`{% url 'wishlist:add_wishlist_ajax' %}`">Tambah Barang Wishlist</button>

</div>
{% endblock content %}

wishlist/templates/wishlist_ajax_submit.html
{% extends 'base.html' %}
{% block content %}
<!-- buat get sm post -->
{% block meta %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!-- contoh  -->
<script>
  
    $("#sbtn-add").click(function(){
      $.post("{% url 'wishlist:add_wishlist_ajax' %}")
      })

    </script>
{% endblock meta %}

<nav class="navbar navbar-expand-lg bg-light ">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Hi, {{nama}}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'example_app:index' %}">Home</a>
            </li>
        </ul>
        <span class="navbar-text">
            <button class="btn btn-dark" onclick="location.href=`{% url 'wishlist:logout' %}`">Logout</button>
        </span>
        </div>
    </div>
</nav>


<div class="container ">

    <form method="POST" >
        {% csrf_token %} 
        <div class="d-flex flex-column gap-3 justify-center m-5">
            {{ form.as_div }}
        </div>
        <button id="btn-add" class="btn btn-primary mx-5">Tambah Barang Wishlist</button>
    </form>
    <button  class="btn btn-secondary mx-5 my-3" onclick="location.href=`{% url 'wishlist:show_wishlist_ajax' %}`">Kembali</button>

</div>
{% endblock content %}